spring.application.name=API-GATEWAY
server.port=8090
spring.main.web-application-type=reactive

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Discovery Locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# BIN SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=bin-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://BIN-MONITORING-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/bins/**

# COLLECTION SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=collection-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://COLLECTION-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/collections/**

# ROUTE SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=route-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ROUTE-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/routes/**

# REPORT SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=report-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://REPORT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/reports/**

# AUTH SERVICE
spring.cloud.gateway.server.webflux.routes[4].id=auth-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/auth/**

# CORS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true